# Generated by Django 5.2 on 2025-04-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('dia_aula_experimental', models.DateField()),
                ('horario_aula_experimental', models.TimeField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('compareceu', 'Compareceu'), ('não compareceu', 'Não Compareceu'), ('matriculado', 'Matriculado'), ('recusado', 'Recusado')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
