# Generated by Django 5.2 on 2025-05-15 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_alter_matricula_aluno_alter_pagamento_aluno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presenca',
            name='confirmado_funcionario',
        ),
        migrations.AddField(
            model_name='presenca',
            name='confirmado_por',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo__in': ['gerente', 'professor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
