# Generated by Django 5.2 on 2025-04-29 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_matricula_presenca'),
        ('turmas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='precadastro',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='turmas.turma'),
        ),
        migrations.AlterField(
            model_name='precadastro',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='precadastro',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('compareceu', 'Compareceu'), ('matriculado', 'Matriculado'), ('nao_compareceu', 'Não Compareceu'), ('nao_quiser_matricular', 'Não Quis Matricular')], default='pendente', max_length=30),
        ),
        migrations.AddField(
            model_name='matricula',
            name='aluno',
            field=models.ForeignKey(limit_choices_to={'tipo_usuario': 'aluno'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.turma'),
        ),
        migrations.AddField(
            model_name='presenca',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='alunos.matricula'),
        ),
    ]
