# Generated by Django 5.2 on 2025-05-15 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_remove_presenca_confirmado_funcionario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='turma',
        ),
        migrations.RemoveField(
            model_name='presenca',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='presenca',
            name='confirmado_por',
        ),
        migrations.RemoveField(
            model_name='presenca',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='presenca',
            name='hora',
        ),
        migrations.AddField(
            model_name='precadastro',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='precadastro',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='presenca',
            name='usuario',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'aluno'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='presenca',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Pagamento',
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='Matricula',
        ),
    ]
