# Generated by Django 5.2 on 2025-05-16 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_remove_aluno_usuario_remove_matricula_aluno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presenca',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='PreCadastro',
        ),
        migrations.DeleteModel(
            name='Presenca',
        ),
    ]
