# Generated by Django 5.2 on 2025-04-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
