# Generated by Django 5.2 on 2025-05-15 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_funcionario_ativo_funcionario_despesa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='turmas',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='user',
        ),
    ]
