# Generated by Django 5.2 on 2025-05-15 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_remove_despesa_funcionario_despesa_usuario_and_more'),
        ('funcionarios', '0005_remove_funcionario_turmas_remove_funcionario_user'),
        ('turmas', '0004_diasemana_alter_turma_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
