# Generated by Django 5.2 on 2025-07-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0008_alter_presenca_turma_alter_presenca_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenca',
            name='checkin_realizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presenca',
            name='presenca_confirmada',
            field=models.BooleanField(default=False),
        ),
    ]
