# Generated by Django 5.2 on 2025-05-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centrodetreinamento',
            options={'verbose_name_plural': 'Centros de Treinamento'},
        ),
        migrations.AddField(
            model_name='centrodetreinamento',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='centrodetreinamento',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
