# Generated by Django 5.2 on 2025-10-15 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0002_alter_centrodetreinamento_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título da foto', max_length=200)),
                ('descricao', models.TextField(blank=True, help_text='Descrição ou legenda da foto')),
                ('imagem', models.ImageField(help_text='Imagem da galeria', upload_to='galeria_fotos/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True, help_text='Se a foto está ativa/visível')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_galeria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foto da Galeria',
                'verbose_name_plural': 'Fotos da Galeria',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='SuperaNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título da notícia', max_length=200)),
                ('descricao', models.TextField(help_text='Descrição ou conteúdo da notícia')),
                ('imagem', models.ImageField(help_text='Imagem da notícia', upload_to='supera_news/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True, help_text='Se a notícia está ativa/visível')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supera News',
                'verbose_name_plural': 'Supera News',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
