# Generated by Django 4.2.7 on 2026-01-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0010_turma_professores_m2m'),
        ('ct', '0003_galeriafoto_superanews'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrodetreinamento',
            name='dias_semana',
            field=models.ManyToManyField(blank=True, help_text='Dias em que o CT funciona', related_name='centros_treinamento', to='turmas.diasemana'),
        ),
    ]
