# Generated by Django 4.2.7 on 2026-03-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0004_centrodetreinamento_dias_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrodetreinamento',
            name='sem_financeiro',
            field=models.BooleanField(default=False, help_text='Se ativo, alunos vinculados a este CT não terão mensalidades criadas.'),
        ),
    ]
