# Generated by Django 4.2.7 on 2026-03-31 23:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0005_add_sem_financeiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidaturaTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('tipo_vaga', models.CharField(choices=[('professor', 'Professor(a)'), ('estagiario', 'Estagiário(a)')], max_length=20)),
                ('interesse_praia', models.BooleanField(default=True)),
                ('interesse_quadra', models.BooleanField(default=True)),
                ('periodo_ed_fis', models.CharField(blank=True, max_length=80)),
                ('mensagem', models.TextField(blank=True)),
                ('curriculo', models.FileField(upload_to='candidaturas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Candidatura (Trabalhe conosco)',
                'verbose_name_plural': 'Candidaturas (Trabalhe conosco)',
                'ordering': ['-data_envio'],
            },
        ),
    ]
