# Generated by Django 5.2 on 2025-05-20 20:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0005_alter_turma_professor'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ficha_medica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome_responsavel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone_emergencia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone_responsavel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('gerente', 'Gerente'), ('professor', 'Professor'), ('aluno', 'Aluno')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.CreateModel(
            name='PreCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Formato inválido. Use (21)00000-0000.', regex='^\\(\\d{2}\\)\\d{5}-\\d{4}$')])),
                ('data_de_nascimento', models.DateField(null=True)),
                ('email', models.EmailField(default='pendente', error_messages={'blank': 'O campo e-mail não pode estar vazio.', 'null': 'O campo e-mail não pode ser nulo.', 'unique': 'Esse e-mail já está cadastrado.'}, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('compareceu', 'Compareceu'), ('matriculado', 'Matriculado'), ('nao_compareceu', 'Não Compareceu'), ('desistiu', 'Desistiu')], default='pendente', max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turmas.turma')),
            ],
        ),
    ]
