# Generated by Django 5.2 on 2025-05-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('gerente', 'Gerente'), ('professor', 'Professor'), ('aluno', 'Aluno')], max_length=20),
        ),
    ]
