# Generated by Django 5.2 on 2025-05-21 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0002_alter_centrodetreinamento_options_and_more'),
        ('usuarios', '0002_usuario_data_nascimento_usuario_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ct.centrodetreinamento'),
        ),
    ]
