# Generated by Django 5.2 on 2025-05-22 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_ct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='precadastro',
            old_name='data_de_nascimento',
            new_name='data_nascimento',
        ),
    ]
