# Generated by Django 5.2 on 2025-05-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_rename_data_de_nascimento_precadastro_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='precadastro',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
