# Generated by Django 5.2 on 2025-05-22 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_precadastro_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precadastro',
            name='status',
        ),
        migrations.AddField(
            model_name='precadastro',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
