# Generated by Django 5.2 on 2025-05-28 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_remove_precadastro_status_precadastro_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ct',
        ),
    ]
