# Generated by Django 5.2 on 2025-06-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_usuario_ct'),
    ]

    operations = [
        migrations.AddField(
            model_name='precadastro',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('matriculado', 'Matriculado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
    ]
