# Generated by Django 5.2 on 2025-05-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuario_username_precadastro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precadastro',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='precadastro',
            name='usuario',
        ),
        migrations.AddField(
            model_name='precadastro',
            name='data_de_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
