# Generated by Django 5.2 on 2025-05-19 19:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0005_alter_turma_professor'),
        ('usuarios', '0008_remove_precadastro_cpf_remove_precadastro_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precadastro',
            name='data_de_nascimento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='precadastro',
            name='email',
            field=models.EmailField(default='pendente', error_messages={'blank': 'O campo e-mail não pode estar vazio.', 'null': 'O campo e-mail não pode ser nulo.', 'unique': 'Esse e-mail já está cadastrado.'}, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='precadastro',
            name='telefone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Formato inválido. Use (21)00000-0000.', regex='^\\(\\d{2}\\)\\d{5}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='precadastro',
            name='turma',
            field=models.ForeignKey(to="turmas.turma", on_delete=models.CASCADE, null=True, blank=True),
        ),
    ]
