# Generated by Django 5.2 on 2025-07-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_precadastro_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dia_vencimento',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Dia do vencimento da mensalidade (1-31)', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='valor_mensalidade',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor personalizado da mensalidade do aluno', max_digits=7, null=True),
        ),
    ]
