# Generated by Django 5.2 on 2025-07-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_usuario_dia_vencimento_usuario_valor_mensalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pix_professor',
            field=models.CharField(blank=True, help_text='Chave PIX do professor para pagamentos', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='salario_professor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Salário do professor', max_digits=10, null=True),
        ),
    ]
