# Generated by Django 5.2 on 2025-07-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_usuario_pix_professor_usuario_salario_professor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='precadastro',
            old_name='nome',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='precadastro',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
