# Generated by Django 5.2 on 2026-01-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_add_contrato_aceite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='parq_question_1',
            field=models.BooleanField(default=False, help_text='PAR-Q: Algum médico já disse que você possui algum problema de coração ou pressão arterial, e que somente deveria realizar atividade física supervisionado por profissionais de saúde?'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='parq_question_2',
            field=models.BooleanField(default=False, help_text='PAR-Q: Você sente dores no peito quando pratica atividade física?'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='parq_question_3',
            field=models.BooleanField(default=False, help_text='PAR-Q: No último mês, você sentiu dores no peito ao praticar atividade física?'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='parq_question_4',
            field=models.BooleanField(default=False, help_text='PAR-Q: Você apresenta algum desequilíbrio devido à tontura e/ou perda momentânea da consciência?'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='parq_question_5',
            field=models.BooleanField(default=False, help_text='PAR-Q: Você possui algum problema ósseo ou articular, que pode ser afetado ou agravado pela atividade física?'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='parq_question_6',
            field=models.BooleanField(default=False, help_text='PAR-Q: Você toma atualmente algum tipo de medicação de uso contínuo?'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='parq_question_7',
            field=models.BooleanField(default=False, help_text='PAR-Q: Você realiza algum tipo de tratamento médico para pressão arterial ou problemas cardíacos?'),
        ),
    ]
