# Generated by Django 4.2.7 on 2026-01-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0010_turma_professores_m2m'),
        ('usuarios', '0018_alter_usuario_parq_question_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dias_habilitados',
            field=models.ManyToManyField(blank=True, related_name='alunos_habilitados', to='turmas.diasemana'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='plano',
            field=models.CharField(blank=True, choices=[('3x', '3 vezes na semana'), ('2x', '2 vezes na semana'), ('1x', '1 vez na semana')], help_text='Plano semanal do aluno', max_length=2, null=True),
        ),
    ]
