# Generated by Django 4.2+ - Campo origem no PreCadastro

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_usuario_dias_habilitados_usuario_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='precadastro',
            name='origem',
            field=models.CharField(blank=True, choices=[('aula_experimental', 'Aula experimental'), ('ex_aluno', 'Já foi aluno'), ('formulario', 'Cadastro web')], help_text='Origem do pré-cadastro: aula experimental, ex-aluno ou formulário', max_length=20, null=True),
        ),
    ]
