# Generated by Django 4.2.7 on 2026-03-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_email_nao_unico_menores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precadastro',
            name='origem',
            field=models.CharField(blank=True, choices=[('formulario', 'Pendente'), ('aula_experimental', 'Aula experimental'), ('ex_aluno', 'Ex-aluno')], help_text='Origem do pré-cadastro: aula experimental, ex-aluno ou formulário', max_length=20, null=True),
        ),
    ]
