# Generated by Django 4.2.7 on 2026-03-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_alter_precadastro_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='precadastro',
            name='compareceu_aula_experimental',
            field=models.BooleanField(default=False, help_text='Professor marcou comparecimento na aula experimental'),
        ),
        migrations.AddField(
            model_name='precadastro',
            name='data_aula_experimental',
            field=models.DateField(blank=True, help_text='Data escolhida pelo cliente para a aula experimental', null=True),
        ),
        migrations.AddField(
            model_name='precadastro',
            name='reagendou_aula_experimental',
            field=models.BooleanField(default=False, help_text='Cliente já fez um reagendamento (máx. 1)'),
        ),
    ]
