# Generated by Django 4.2.7 on 2026-03-23 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_aula_experimental_campos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushTokenExpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens_expo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token push Expo',
                'verbose_name_plural': 'Tokens push Expo',
            },
        ),
    ]
