# Generated by Django 4.2.7 on 2026-03-23 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0025_precadastro_telefone_digitos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precadastro',
            name='telefone',
            field=models.CharField(help_text='Apenas números, com DDD (10 ou 11 dígitos).', max_length=20, validators=[django.core.validators.RegexValidator(message='Informe o telefone com DDD: 10 ou 11 dígitos (apenas números).', regex='^\\d{10,11}$')]),
        ),
    ]
