# Generated by Django 4.2.7 on 2026-03-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0027_precadastro_matriculado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='data_inativacao',
            field=models.DateField(blank=True, help_text='Data em que o aluno foi inativado (desistência). Preenchida automaticamente ao marcar ativo=False.', null=True),
        ),
    ]
