# Generated by Django 5.2 on 2025-05-12 13:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
        ('funcionarios', '0003_alter_funcionario_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('salario', 'Salário de Funcionário'), ('aluguel', 'Aluguel'), ('materiais', 'Compra de Materiais'), ('outros', 'Outros')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.funcionario')),
            ],
        ),
    ]
