# Generated by Django 5.2 on 2025-05-21 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_remove_despesa_funcionario_despesa_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensalidade',
            name='aluno',
            field=models.ForeignKey(limit_choices_to={'tipo': 'aluno'}, on_delete=django.db.models.deletion.CASCADE, related_name='mensalidades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='data_inicio',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=7),
        ),
    ]
