# Generated by Django 5.2 on 2025-05-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_salario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salario',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=20),
        ),
    ]
