# Generated by Django 5.2 on 2025-06-17 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_alter_salario_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransacaoPix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pix', models.TextField()),
                ('qr_code', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('expirado', 'Expirado')], default='pendente', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_expiracao', models.DateTimeField()),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('identificador_externo', models.CharField(max_length=100, unique=True)),
                ('mensalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes_pix', to='financeiro.mensalidade')),
            ],
            options={
                'verbose_name': 'Transação PIX',
                'verbose_name_plural': 'Transações PIX',
            },
        ),
    ]
