# Generated by Django 5.2 on 2025-07-18 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_transacaopix'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransacaoBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('expirado', 'Expirado'), ('processando', 'Processando')], default='pendente', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_expiracao', models.DateTimeField()),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('identificador_externo', models.CharField(max_length=100, unique=True)),
                ('preference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_url', models.URLField(blank=True, null=True)),
                ('metodo_pagamento', models.CharField(blank=True, max_length=50, null=True)),
                ('mensalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes_bancarias', to='financeiro.mensalidade')),
            ],
            options={
                'verbose_name': 'Transação Bancária',
                'verbose_name_plural': 'Transações Bancárias',
            },
        ),
    ]
