# Generated by Django 5.2 on 2025-10-24 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0009_transacaobancaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransacaoC6Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pix', 'PIX'), ('boleto', 'Boleto'), ('cartao', 'Cartão de Crédito/Débito'), ('transferencia', 'Transferência Bancária')], default='pix', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('expirado', 'Expirado'), ('processando', 'Processando'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('txid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('chave_pix', models.CharField(blank=True, max_length=100, null=True)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('codigo_pix', models.TextField(blank=True, null=True)),
                ('payment_url', models.URLField(blank=True, null=True)),
                ('boleto_url', models.URLField(blank=True, null=True)),
                ('boleto_codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_expiracao', models.DateTimeField()),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('resposta_api', models.JSONField(blank=True, null=True)),
                ('erro_api', models.TextField(blank=True, null=True)),
                ('mensalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes_c6', to='financeiro.mensalidade')),
            ],
            options={
                'verbose_name': 'Transação C6 Bank',
                'verbose_name_plural': 'Transações C6 Bank',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
