# Generated by Django 4.2.7 on 2026-03-23 00:28

from django.db import migrations, models
import django.db.models.functions.datetime


def _dedupe_mensalidades_mesmo_aluno_mes(apps, schema_editor):
    """
    Remove mensalidades duplicadas (mesmo aluno, mesmo ano/mês de data_vencimento).
    Mantém uma: prioriza status=pago; senão o menor id. Reaponta transações para a mantida.
    """
    Mensalidade = apps.get_model('financeiro', 'Mensalidade')
    TransacaoC6Bank = apps.get_model('financeiro', 'TransacaoC6Bank')
    TransacaoPix = apps.get_model('financeiro', 'TransacaoPix')
    TransacaoBancaria = apps.get_model('financeiro', 'TransacaoBancaria')

    from collections import defaultdict

    grouped = defaultdict(list)
    for m in Mensalidade.objects.all().order_by('id').iterator():
        key = (m.aluno_id, m.data_vencimento.year, m.data_vencimento.month)
        grouped[key].append(m.id)

    for _key, ids in grouped.items():
        if len(ids) <= 1:
            continue
        rows = list(Mensalidade.objects.filter(id__in=ids).order_by('id'))
        keeper_id = None
        for r in rows:
            if r.status == 'pago':
                keeper_id = r.id
                break
        if keeper_id is None:
            keeper_id = min(ids)
        for rid in ids:
            if rid == keeper_id:
                continue
            TransacaoC6Bank.objects.filter(mensalidade_id=rid).update(mensalidade_id=keeper_id)
            TransacaoPix.objects.filter(mensalidade_id=rid).update(mensalidade_id=keeper_id)
            TransacaoBancaria.objects.filter(mensalidade_id=rid).update(mensalidade_id=keeper_id)
            Mensalidade.objects.filter(id=rid).delete()


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0012_mensalidade_valor_pago'),
    ]

    operations = [
        migrations.RunPython(_dedupe_mensalidades_mesmo_aluno_mes, _noop),
        migrations.AddConstraint(
            model_name='mensalidade',
            constraint=models.UniqueConstraint(
                models.F('aluno'),
                django.db.models.functions.datetime.ExtractYear('data_vencimento'),
                django.db.models.functions.datetime.ExtractMonth('data_vencimento'),
                name='uniq_mensalidade_aluno_ano_mes',
            ),
        ),
    ]
