# Generated by Django 5.2 on 2025-05-11 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ct', '0001_initial'),
        ('funcionarios', '0002_funcionario_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dia_semana', models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10)),
                ('horario', models.TimeField()),
                ('capacidade_maxima', models.PositiveIntegerField(default=0)),
                ('ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ct.centrodetreinamento')),
                ('professor', models.ForeignKey(blank=True, limit_choices_to={'cargo': 'professor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas', to='funcionarios.funcionario')),
            ],
            options={
                'verbose_name_plural': 'Turmas',
                'ordering': ['dia_semana', 'horario'],
                'unique_together': {('ct', 'dia_semana', 'horario')},
            },
        ),
    ]
