# Generated by Django 5.2 on 2025-05-14 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_funcionario_ativo_funcionario_despesa_and_more'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='turmas_lecionadas', to='funcionarios.funcionario'),
        ),
    ]
