# Generated by Django 5.2 on 2025-05-14 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_funcionario_ativo_funcionario_despesa_and_more'),
        ('turmas', '0002_alter_turma_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(blank=True, limit_choices_to={'cargo': 'professor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.funcionario'),
        ),
    ]
