# Generated by Django 5.2 on 2025-04-30 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0001_initial'),
        ('funcionarios', '0001_initial'),
        ('turmas', '0003_centrodetreinamento_delete_centrotreinamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas', to='funcionarios.funcionario'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='ct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ct.centrotreinamento'),
        ),
    ]
