# Generated by Django 5.2 on 2025-05-15 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0002_alter_centrodetreinamento_options_and_more'),
        ('turmas', '0003_alter_turma_professor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={'ordering': ['horario'], 'verbose_name_plural': 'Turmas'},
        ),
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together={('ct', 'horario')},
        ),
        migrations.AlterField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'professor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turma',
            name='dias_semana',
            field=models.ManyToManyField(to='turmas.diasemana'),
        ),
        migrations.RemoveField(
            model_name='turma',
            name='dia_semana',
        ),
    ]
