# Generated by Django 5.2 on 2025-05-21 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0005_alter_turma_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='nome',
        ),
    ]
