# Generated by Django 5.2 on 2025-06-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0007_turma_alunos'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
