# Generated by Django 5.2 on 2025-10-13 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0005_populate_dias_semana'),
        ('turmas', '0008_turma_ativo'),
    ]

    operations = [
    ]
