# Generated by Django - Campo faixa_etaria no Turma

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0010_turma_professores_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='faixa_etaria',
            field=models.CharField(
                choices=[('kids', 'Kids (até 12 anos)'), ('teen', 'Teen (até 18 anos)'), ('adultos', 'Adultos (maiores de 18 anos)')],
                default='adultos',
                help_text='Kids: até 12 anos | Teen: até 18 anos | Adultos: maiores de 18',
                max_length=20
            ),
        ),
    ]
