# Generated by Django 6.0.4 on 2026-05-25 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ct', '0006_candidatura_trabalho'),
        ('turmas', '0012_turma_faixas_multiplas'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroWellhub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wellhub_user_id', models.CharField(blank=True, db_index=True, default='', help_text='Identificador estável do usuário na Wellhub (gpw-id, gympass-id, etc.).', max_length=128)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telefone', models.CharField(blank=True, default='', max_length=20)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cadastro Wellhub',
                'verbose_name_plural': 'Cadastros Wellhub',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='WellhubWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=128, unique=True)),
                ('event_type', models.CharField(blank=True, default='', max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento webhook Wellhub',
                'verbose_name_plural': 'Eventos webhook Wellhub',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='WellhubGymConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_id', models.PositiveIntegerField(help_text='Identificador da academia na Wellhub.')),
                ('product_id', models.PositiveIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('ct', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wellhub_config', to='ct.centrodetreinamento')),
            ],
            options={
                'verbose_name': 'Configuração Wellhub (CT)',
                'verbose_name_plural': 'Configurações Wellhub (CT)',
            },
        ),
        migrations.CreateModel(
            name='WellhubSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aula', models.DateField()),
                ('occur_date', models.DateTimeField()),
                ('wellhub_slot_id', models.CharField(blank=True, default='', max_length=64)),
                ('total_capacity', models.PositiveIntegerField(default=5)),
                ('total_booked', models.PositiveIntegerField(default=0)),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
                ('sync_status', models.CharField(choices=[('pending', 'Pendente'), ('ok', 'OK'), ('error', 'Erro')], default='pending', max_length=16)),
                ('sync_error', models.TextField(blank=True, default='')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellhub_slots', to='turmas.turma')),
            ],
            options={
                'verbose_name': 'Slot Wellhub',
                'verbose_name_plural': 'Slots Wellhub',
                'ordering': ['occur_date'],
                'unique_together': {('turma', 'data_aula')},
            },
        ),
        migrations.CreateModel(
            name='WellhubBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wellhub_booking_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('requested', 'Solicitada'), ('confirmed', 'Confirmada'), ('rejected', 'Rejeitada'), ('cancelled', 'Cancelada'), ('late_cancelled', 'Cancelamento tardio')], default='requested', max_length=20)),
                ('late_cancel', models.BooleanField(default=False)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cadastro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='wellhub.cadastrowellhub')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='wellhub.wellhubslot')),
            ],
            options={
                'verbose_name': 'Reserva Wellhub',
                'verbose_name_plural': 'Reservas Wellhub',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='WellhubTurmaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wellhub_class_id', models.CharField(blank=True, default='', max_length=64)),
                ('publicar_wellhub', models.BooleanField(default=False)),
                ('cota_wellhub', models.PositiveIntegerField(default=5)),
                ('turma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wellhub_config', to='turmas.turma')),
            ],
            options={
                'verbose_name': 'Configuração Wellhub (Turma)',
                'verbose_name_plural': 'Configurações Wellhub (Turma)',
            },
        ),
    ]
